Update dark_theme.scss
wallabag/wallabag pull request #4921
Opened 2021-01-08 10:23 UTC by techexo

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Dark theme update to fix most of the issues seen in https://github.com/wallabag/wallabag/issues/4898

2021-01-08 10:42 UTC, j0k3r requested changes
You should update assets using `yarn build:prod` to fix the only red build.

2021-01-08 10:42 UTC, j0k3r commented on app/Resources/static/themes/material/css/dark_theme.scss
> +}
Put a new line at the end of the file

2021-01-08 12:07 UTC, techexo commented on app/Resources/static/themes/material/css/dark_theme.scss
> +}
Commit abed407

2021-01-08 12:17 UTC, techexo commented
@j0k3r I don't get what's going on at the moment. I added the EOF newline as requested and while it passes without issue `yarn build:prod` on my wallabag instance, the Building assets test doesn't pass on Github. Am I missing something here?

2021-01-08 12:35 UTC, j0k3r commented
If the build assets fail, it means there are some difference between was is committed and what `yarn build:prod` is generating.
To fix that, you have to run `yarn build:prod` locally and commits generated assets files.

2021-01-09 22:09 UTC, techexo commented
I did what was requested but I don't know how to reload tests on this PR to check if the assets are OK or not this time. I added the web/wallasets/ files that were generated by yarn build:prod to my commit.

2021-01-12 10:49 UTC, nicosomb commented
@techexo could you run a `yarn build:prod` and commit the 2 changed files please?

2021-01-24 14:39 UTC, Kdecherf commented
I've resolved the conflict and pushed the last version of compiled assets.

Here are two screenshots to compare the change (left is before, right is after):

![2021-01-24-153623_2557x1308](https://user-images.githubusercontent.com/226063/105633688-57522180-5e5a-11eb-930b-51b84b42fb53.png)

![2021-01-24-153634_2543x1299](https://user-images.githubusercontent.com/226063/105633689-58834e80-5e5a-11eb-8117-c47d772d575f.png)

2021-01-24 14:40 UTC, Kdecherf approved these changes

2021-01-24 16:00 UTC, Simounet commented
I updated the code with a PR on his repository. https://github.com/techexo/wallabag/pull/1

2021-01-24 16:03 UTC, Kdecherf commented
@Simounet woops, you may need to rebase your own PR now

2021-01-24 20:14 UTC, j0k3r commented
Should we take care of that?

2021-01-25 19:34 UTC, Kdecherf commented
@Simounet @j0k3r we could merge this PR as-is if it's ok for you, then @Simounet you could improve it via a new PR on this repo.

2021-01-26 08:16 UTC, j0k3r approved these changes
I agree @Kdecherf

2021-01-26 08:17 UTC, merged