Fix tests
wallabag/wallabag pull request #7577
Opened 2024-07-12 15:08 UTC by j0k3r

Looks like lemonde.fr doesn't work anymore in wallabag for test. Switching to an other great media.

Also update site configs.

2024-07-13 05:50 UTC, nicosomb submitted a review, later dismissed

2024-07-13 05:51 UTC, nicosomb commented
some tests are 🔴

2024-07-14 00:12 UTC, Kdecherf requested changes
We should keep 2 entries in the import tests (I guess that's why they're failing btw)

2024-07-15 08:51 UTC, Kdecherf approved these changes

2024-07-15 08:52 UTC, merged