Backport 2.6.10 into master
wallabag/wallabag pull request #7796
Opened 2024-11-11 08:27 UTC by Kdecherf

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | 
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

2024-11-11 20:13 UTC, yguedidi requested changes

2024-11-11 20:13 UTC, yguedidi commented on web/wallassets/41a1d465797f51702171.otf
Not sure this should be commited

2024-11-11 20:19 UTC, Kdecherf commented on web/wallassets/41a1d465797f51702171.otf
It comes from bd8ccf924f4ae78be407b151b668679edd511e0b #7754 
@nicosomb is this an error?

2024-11-12 15:57 UTC, j0k3r commented on web/wallassets/41a1d465797f51702171.otf
Hum, assets should not be in the repo anymore.
What if you remove it and then generated assets, does that file exist?

2024-11-15 22:57 UTC, Kdecherf commented on web/wallassets/41a1d465797f51702171.otf
As it was a PITA to redo the merge commit, I went with a separate commit to remove it

2024-11-15 23:10 UTC, Kdecherf commented
I'm not a big fan of what I've done but here we go, I've "rebased" my PR to match the current state of `master` with a merge commit. I think it is the quickest option instead of redoing merge conflict resolution.

2024-11-16 20:26 UTC, yguedidi approved these changes
what a work! congrats for this great work!

2024-11-16 20:26 UTC, yguedidi commented on src/Command/Import/ImportCommand.php
> +        OmnivoreImport $omnivoreImport
nitpick: would have added it after DeliciousImport, like the property and initialization in constructor, and like it's done in 2.6 😅

2024-11-17 10:04 UTC, merged