Use Graby's http headers configuration for the authentication request
wallabag/wallabag pull request #7920
Opened 2024-12-26 14:02 UTC by e-adrien

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

This PR is related to https://github.com/wallabag/wallabag/issues/7878
Currently, if a user defines a User-Agent for a website Wallabag uses this User-Agent only to get the content, not for the authentication request.

This PR pass the HTTP headers defined for the website to the authentication request.

2024-12-26 22:37 UTC, yguedidi requested changes
I think this deserves to be tested

2024-12-26 22:37 UTC, yguedidi commented on src/SiteConfig/LoginFormAuthenticator.php
> +            ['body' => $postFields, 'allow_redirects' => true, 'verify' => false] + ($siteConfig->hasHttpHeaders() ? ['headers' => $siteConfig->getHttpHeaders()] : []),
for code readability I'd set a `$param` variable with base values, then use an explicit `if` statement to add the `headers` key

2025-01-06 14:44 UTC, j0k3r commented
Maybe you can add a test in `tests/SiteConfig/LoginFormAuthenticatorTest.php`?

@Kdecherf can you test it locally? I don't have a subscription available atm.

2025-01-06 17:53 UTC, e-adrien commented
Hi @j0k3r, I added a test in `tests/SiteConfig/LoginFormAuthenticatorTest.php`.

2025-02-18 10:44 UTC, e-adrien commented
Hi @j0k3r 
I rebased this PR to fix issues after the merge of #7947 
Let me know if you want changes / tests / docs...

2025-02-18 21:00 UTC, yguedidi requested changes

2025-02-19 11:53 UTC, yguedidi requested changes
sorry for this new round of review with new idea 😅

2025-02-19 11:53 UTC, yguedidi commented on src/SiteConfig/GrabySiteConfigBuilder.php
> +    protected function processHeaders(array $configHeaders): array
with fresh new eyes I think this should not be done here, so that the SiteConfig kept original header names.
should be a private function LoginFormAuthenticator, what do you think?

2025-02-19 11:53 UTC, yguedidi commented on tests/SiteConfig/LoginFormAuthenticatorTest.php
> +                'HTTP_user-agent' => 'Wallabag (Guzzle/5)',
by moving to LoginFormAuthenticator this become
```suggestion
                'user-agent' => 'Wallabag (Guzzle/5)',
```

2025-02-19 11:53 UTC, yguedidi commented on tests/SiteConfig/LoginFormAuthenticatorTest.php
> +                    'HTTP_user-agent' => 'Wallabag (Guzzle/5)',
but this stays as it is

2025-02-19 11:53 UTC, yguedidi commented on tests/SiteConfig/SiteConfigTest.php
> +                'HTTP_user-agent' => 'Wallabag (Guzzle/5)',
```suggestion
                'user-agent' => 'Wallabag (Guzzle/5)',
```

2025-02-19 12:49 UTC, e-adrien commented on src/SiteConfig/GrabySiteConfigBuilder.php
> +    protected function processHeaders(array $configHeaders): array
You're right, it's a bit weird to have it here.

2025-02-19 12:57 UTC, e-adrien commented
No worries, I made the changes. 😄

2025-02-19 19:19 UTC, yguedidi requested changes
LGTM, please squash, looks nice now!

2025-02-20 07:51 UTC, e-adrien commented
Rebased & squashed 🙂

2025-02-20 08:06 UTC, j0k3r approved these changes
Good job here.
Should you update the site config as well (maybe to remove `test`)?

https://github.com/fivefilters/ftr-site-config/blob/7a8b269a86b4e5201cfa59af9206105702b9d4f3/lesjours.fr.txt#L1

2025-02-20 09:08 UTC, e-adrien commented
Thanks.
I've opened a PR https://github.com/fivefilters/ftr-site-config/pull/1557 to remove the `http_header(User-Agent)` rule.

2025-02-20 09:24 UTC, yguedidi approved these changes

2025-02-20 09:24 UTC, merged